spring:
  application:
    name: yu-ai-code-mother-backen
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yu_ai_code_mother
    username: root
    password: 1234
  data:
    redis:
      host: localhost
      port: 6379
      ttl: 3600
  session:
    store-type: redis
    timeout: 259200

server:
  port: 8123
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 259200

springdoc:
  group-configs:
    - group: "default"
      packages-to-scan: com.yupi.yuaicodemother.controller

knife4j:
  enable: true
  setting:
    language: zh_cn

langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      model-name: deepseek-chat
      max-tokens: 8192
      strict-json-schema: true
      log-requests: true
      log-responses: true
      response-format: json_object
      api-key: sk-efa8ced4b5564162a0a05913c35f6ebd
    streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-efa8ced4b5564162a0a05913c35f6ebd
      model-name: deepseek-chat
      max-tokens: 8192
      log-requests: true
      log-responses: true

