spring:
  application:
    name: yu-ai-code-mother-backen
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yu_ai_code_mother
    username: root
    password: 1234
  data:
    redis:
      host: localhost
      port: 6379
      ttl: 3600
      database: 0
  session:
    store-type: redis
    timeout: 259200

server:
  port: 8123
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 259200

springdoc:
  group-configs:
    - group: "default"
      packages-to-scan: com.yupi.yuaicodemother.controller

knife4j:
  enable: true
  setting:
    language: zh_cn

langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      model-name: deepseek-chat
      max-tokens: 8192
      strict-json-schema: true
      log-requests: true
      log-responses: true
      response-format: json_object
      api-key: <api-key>
    streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: <api-key>
      model-name: deepseek-chat
      max-tokens: 8192
      log-requests: true
      log-responses: true
    reasoning-streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: <Your API Key>
      model-name: deepseek-reasoner
      max-tokens: 32768
      temperature: 0.1
      log-requests: true
      log-responses: true
    # 智能路由 AI 模型配置（用于简单的分类任务）
    routing-chat-model:
      base-url: https://api.deepseek.com
      api-key: <Your API Key>
      model-name: deepseek-chat
      log-requests: true
      log-responses: true
minio:
  endpoint: http://119.45.112.127:19000
  access-key: minio
  secret-key: 050312hz
  bucket-name: yuai


