spring:
  application:
    name: yu-ai-code-mother-backen
server:
  port: 8123
  servlet:
    context-path: /api
springdoc:
  group-configs:
    -group: "default"
    packages-to-scan: com.yupi.yuaicodemother.controller
knife4j:
  enable: true
  setting:
    language: zh_cn
